# Load profile test2
set scenario_results($scenario_index) "FAIL - Check test2 environment"

send "switch_profile test2\n"
expect {
    timeout abort
    "#"
}

# Test variable not set in profile test2
send "echo \${check_var_test1:-\$var_unset}\n"
expect {
    timeout abort
    "variable not setted"
}

# Test variable set in profile test2
send "echo \$check_var_test2\n"
expect {
    timeout abort
    "test2 variable"
}

# Test variable set in profile test2
send "echo \$check_var_common\n"
expect {
    timeout abort
    "test2 common"
}

set scenario_results($scenario_index) "PASS - Check test2 environment"
set scenario_index [ expr $scenario_index + 1]
