# Load profile test1
set scenario_results($scenario_index) "FAIL - Reset saved profile"

send "switch_profile test1\n"
expect {
    timeout abort
    "#"
}

send "cat ~/.bash_saved_profile\n"
expect {
    timeout abort
    "export BASH_CURRENT_PROFILE=test1"
}

send "switch_profile -d\n"
expect {
    timeout abort
    "#"
}

send "cat ~/.bash_saved_profile\n"
expect {
    timeout abort
    "unset BASH_CURRENT_PROFILE"
}

set scenario_results($scenario_index) "PASS - Reset saved profile"
set scenario_index [ expr $scenario_index + 1]
