set scenario_results($scenario_index) "FAIL - Temporary profile check"

send "switch_profile -d\n"
expect {
    timeout abort
    "#"
}

send "switch_profile -t test1\n"
expect {
    timeout abort
    "#"
}

# Check we are using test1
send "echo profile:\$SWITCH_PROFILE_CURRENT\n"
expect {
    timeout abort
    "profile:test1"
}

send "cat ~/.bash_saved_profile\n"
expect {
    timeout abort
    "unset SWITCH_PROFILE_CURRENT"
}

set scenario_results($scenario_index) "PASS - Temporary profile check"
set scenario_index [ expr $scenario_index + 1]
