set scenario_results($scenario_index) "FAIL - Keep profile check"

send "switch_profile test1\n"
expect {
    timeout abort
    "#"
}

send "switch_profile -k test2\n"
expect {
    timeout abort
    "#"
}

send "echo \$check_var_test1\n"
expect {
    timeout abort
    "test1 variable"
}

send "echo \$check_var_test2\n"
expect {
    timeout abort
    "test2 variable"
}

send "echo \$check_var_common\n"
expect {
    timeout abort
    "test2 common"
}
set scenario_results($scenario_index) "PASS - Keep profile check"
set scenario_index [ expr $scenario_index + 1]
