---
version: '3.7'
services:
  shell:
    hostname: shell
    container_name: shell
    image: bash:5
    working_dir: /root
    volumes:
      - type: bind
        source: $PWD/bash_profile_switcher.sh
        target: /root/bash_profile_switcher.sh
        read_only: true
      - type: bind
        source: $PWD/tests/bashrc
        target: /root/.bashrc
        read_only: true
      - type: bind
        source: $PWD/tests/profiles/
        target: /root/.bash_profile.d/
        read_only: true
