#!/usr/bin/expect -f
set timeout 2
set send_human {.1 .3 1 .05 2}
set scenario_index 0

proc print_results {} {
    global scenario_results
    puts "\n--- TEST RESULTS ---"
    for { set index 0 } { $index < [array size scenario_results] } { incr index } {
        set sn [format {%02d} [ expr $index + 1]]
        puts "Scenario $sn: $scenario_results($index)"
    }
}

proc abort {} {
    print_results
    send "exit\n"
    send "exit\n"
    sleep 1
    puts "ERROR: Test Failure"
    close
    exit 1
}

spawn docker-compose run --rm shell
sleep 2
expect "#"

source ./tests/scenarios/01-list-profiles.exp
source ./tests/scenarios/02-autocomplete.exp
source ./tests/scenarios/03-check-var-test1.exp
source ./tests/scenarios/04-check-var-test2.exp
source ./tests/scenarios/05-reset-profile.exp
source ./tests/scenarios/06-temporary-profile.exp
source ./tests/scenarios/07-keep-profile.exp
source ./tests/scenarios/08-unexistent-profile.exp
source ./tests/scenarios/09-reload-list.exp
source ./tests/scenarios/10-check-snippet.exp

send "exit\n"
sleep 1
print_results
puts "OK: Test Success"
close
exit
