#!/usr/bin/expect -f
set timeout 2
set send_human {.1 .3 1 .05 2}

proc abort {s} {
    global scenario_results
    set scenario_results($s) "FAIL"
    puts "\n\n--- TEST RESULTS ---\n"
    for { set index 0 } { $index < [array size scenario_results] } { incr index } {
        set sn [ expr $index + 1]
        puts "Scenario $sn: $scenario_results($index)\n"
    }
    send "exit\n"
    send "exit\n"
    sleep 1
    puts "ERROR: Test Failure\n"
    close
    exit 1
}

spawn docker-compose run --rm shell
sleep 2
expect "#"

source ./tests/scenarios/01-list-profiles.exp
source ./tests/scenarios/02-autocomplete.exp
source ./tests/scenarios/03-check-var-test1.exp
source ./tests/scenarios/04-check-var-test2.exp

send "exit\n"
sleep 1
puts "\n\n--- TEST RESULTS ---\n"
for { set index 0 } { $index < [array size scenario_results] } { incr index } {
    set sn [ expr $index + 1]
    puts "Scenario $sn: $scenario_results($index)\n"
}
puts "OK: Test Success\n"
close
exit
