#!/usr/bin/expect -f
set timeout 2
set send_human {.1 .3 1 .05 2}

proc abort {} {
    send "exit\n"
    send "exit\n"
    sleep 1
    close
    exit 1
}

spawn docker-compose run --rm shell
expect "#"

# Test profile list
send "switch_profile -l\n"
expect {
    timeout abort
    "please_fail"
}

# Test autocompletion
send "switch_profile \t"
expect {
    timeout abort
    "test"
}

# Load profile test1
send "1\n"
expect {
    timeout abort
    "#"
}

# Test variable in profile test1
send "echo \$TESTVAR\n"
expect {
    timeout abort
    "testvar setted"
}

# Load profile test2
send "switch_profile test2\n"
expect {
    timeout abort
    "#"
}

# Test variable not set in profile test2
send "echo \${ONLY_TEST1:-\$VARUNSET}\n"
expect {
    timeout abort
    "variable not setted"
}

# Test variable set in profile test2
send "echo \$TESTVAR2\n"
expect {
    timeout abort
    "testvar2 setted"
}

send "exit\n"
sleep 1
close
exit