name: Release
on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Package
        run: |
          make release
          exit $?

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Release version ${{ github.ref }}
          files: bash-profile-switcher_*.tar.gz
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
